# Generated by Django 5.0.4 on 2024-04-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.URLField()),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
