# Generated by Django 5.0.4 on 2024-04-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linky', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
    ]
